AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: road-api
Globals:
  Function:
    Timeout: 300

Resources:
  main:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: main/
      Handler: app.lambda_handler
      Runtime: python3.6
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /{local_authority_id}/{road_name}
            Method: get
